import { Geist, Geist_Mono, Tajawal } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tajawal = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic"], // Make sure to use 'arabic' subset for Tajawal
  weight: ["400", "500", "700"], // Specify the weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * The root layout for the admin dashboard.
 *
 * This component sets up the HTML structure, fonts, and other global styles
 * for the admin-facing pages.
 *
 * @param {object} props - The properties for the component.
 * @param {React.ReactNode} props.children - The child components to be rendered.
 * @returns {React.ReactElement} The root layout component.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tajawal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
